[application]

# App (Project) Name
name = "versions-control-ui"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
#out_dir = "dist"

# resource (public) file folder
asset_dir = "files"

[web.app]
# HTML title tag content
title = "Versions control"


[web.watcher]
# when watcher trigger, regenerate the `index.html`
reload_html = false

# which files or dirs will be watcher monitoring
#watch_path = ["src", "public", "index.html"]

# let the SPA handle any non "/" path
index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["/styled.css", "/app.css"]

# Javascript code file
script = ["/chart.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
